---
# tasks file for enqack.jira

- name: Create run user account
  user:
    name: "{{ jira_run_user }}"
    groups: atlassian
    append: true

- name: Create Jira install directory
  file:
    path: "{{ jira_install_directory }}"
    owner: "{{ jira_run_user }}"
    group: "{{ jira_run_group }}"
    recurse: true

- name: Check for existing Jira archive (local)
  stat:
    path: "{{ role_path }}/files/{{ jira_pkg }}"
  become: false
  run_once: true
  register: package_check
  delegate_to: 127.0.0.1

- name: Download Jira (local)
  get_url:
    url: "{{ jira_download_url }}"
    dest: "{{ role_path }}/files/{{ jira_pkg }}"
    force: true
  become: false
  run_once: true
  delegate_to: 127.0.0.1
  when: not package_check.stat.exists | bool

- name: Extract Jira
  unarchive:
    src: "{{ role_path }}/files/{{ jira_pkg }}"
    dest: "{{ jira_install_directory }}"
    extra_opts: --strip=1

- name: Set Jira home
  copy:
    dest: "{{ jira_install_directory }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    content: jira.home = {{ jira_home_directory }}

- name: Set permissions on install directory
  file:
    path: "{{ jira_install_directory }}"
    owner: "{{ jira_run_user }}"
    group: "{{ jira_run_group }}"
    recurse: true

- name: Set permissions on home directory
  file:
    path: "{{ jira_home_directory }}"
    owner: "{{ jira_run_user }}"
    group: "{{ jira_run_group }}"
    recurse: true

- name: Configure Tomcat
  template:
    src: "{{ role_path }}/templates/server.xml.j2"
    dest: "{{ jira_install_directory }}/conf/server.xml"
    owner: "{{ jira_run_user }}"
    group: "{{ jira_run_group }}"

# - name: Move JNDI mail requirements to default lib path
#   copy:
#     src: "{{ jira_install_directory }}/atlassian-jira/WEB-INF/lib/activation-1.1.1.jar"
#     dest: "{{ jira_install_directory }}/lib/"
#     remote_src: true

- name: Configure database
  template:
    src: "{{ role_path }}/templates/dbconfig.xml.j2"
    dest: "{{ jira_home_directory }}/dbconfig.xml"
    owner: "{{ jira_run_user }}"
    group: "{{ jira_run_group }}"
    mode: 0644

- name: Import Crowd SSO tasks
  import_tasks: crowd_sso.yml

- name: Import systemd tasks
  import_tasks: systemd.yml
